export const generalState = {
  currentUser: null,
  isOnlay: false,
  isAlert: false,
  alertType: "success",
  alertMessage: "",
  currentTimeoutId: "",
  onlayComponent: "",
  requestCounter: 0,
  serverLoan: null,
  currentLoan: null,
  loanPatches: null,
  isBroadcast: false,
  broadcast: null,
  isMagicSpinner: false,
  progressModel: "",
  underwriteMessage1: `If everything looks ok! <br>
        Please click the button below to submit your loan for approval.`,
  underwriteMessage2: "",
  findingsMessages: "",
  isTestingNav: false,
  isHostedMode: false,
  hostedLoanId: "",
  hostedToken: "",
  showNavigation: false,
  nextButtonConditionsOverriden: false,
  currentSectionAndPageData: {},
  currentSection: {},
  currentPage: {},
  currentRuleID: -1,
  appHistoryLength: 0,
  progressModelActive: true // Loan Progress Model is active by default
};
